### ISSUE TITLE
requests.get(REQUEST_URL, get_params) 这句遇到错误

### ISSUE THREAD

**Issue by xuminzhong** [AsiaLi/aliyun_ddns#1]
requests.get(REQUEST_URL, get_params) 这句遇到：
<pre>
Traceback (most recent call last):
  File "aliyun_ddns.py", line 123, in <module>
    update_yun(ip)
  File "aliyun_ddns.py", line 76, in update_yun
    get_resp = requests.get(REQUEST_URL, get_params)
TypeError: get() takes exactly 1 argument (2 given)
</pre>

REQUEST_URL: `https://alidns.aliyuncs.com/`
get_params: `{'SignatureVersion': '1.0', 'DomainName': u'xxx', 'Timestamp': 'xxx', 'Format': 'json', 'SignatureMethod': 'HMAC-SHA1', 'AccessKeyId': u'xxx', 'TypeKeyWord': 'A', 'Version': '2015-01-09', 'Signature': 'xxx', 'Action': 'DescribeDomainRecords', 'SignatureNonce': UUID('xxx')}`

**Comment by limoxi** [comment]
@xuminzhong 更新requests模块
