### ISSUE TITLE
只能解析www域名吗？二级域名怎么办？

### ISSUE THREAD

**Issue by conanliuhuan** [AsiaLi/aliyun_ddns#2]
如题

**Comment by limoxi** [comment]
二级域名、泛解析、手机域名、邮件等都支持，只要记录类型是A记录，暂不支持CNAME和AAAA，因为目前还没这需求

**Comment by Rustic-Z** [comment]
这个issue说的应该是子域名的问题，估计是想修改子域名。不是二级域名
