### ISSUE TITLE
这报错是什么原因

### ISSUE THREAD

**Issue by fanlixings** [AsiaLi/aliyun_ddns#7]
update remote record...
get_records============
{u'Code': u'Forbidden.RAM', u'Message': u"User not authorized to operate on the specified resource, or this API doesn't support RAM.", u'HostId': u'alidns.aliyuncs.com', u'RequestId': u'3AFE62CC-8458-46C7-811A-BA0B60299256'}
Traceback (most recent call last):
  File "aliyun_ddns.py", line 124, in <module>
    update_yun(ip)
  File "aliyun_ddns.py", line 78, in update_yun
    for record in records['DomainRecords']['Record']:
KeyError: 'DomainRecords'

**Comment by charlesld** [comment]
ak sk需要在aliyun 控制台上获取
